---
title: "Introduction to syncomR"
author: "Sudarshan A. Shetty"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to syncomR}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Load libraries

```{r}
library(syncomR)
library(phyloseq)
library(microbiome)

### Assign color and set theme

theme_set(theme_bw())
min_theme <- theme_update(
  #panel.border = element_blank(),
  panel.grid = element_blank(),
  panel.spacing = unit(0, "line"),
  #axis.ticks = element_blank(),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14),
  axis.text = element_text(size = 14),
  axis.title = element_text(size = 14),
  strip.background = element_blank(),
  strip.text = element_text(size = 16),
  legend.key = element_blank()
)
strain.colors<-c(Akkermansia_muciniphila ='#e6194b', Bifidobacterium_adolescentis = '#3cb44b', 
                 Collinsella_aerofaciens= '#ffe119', Bacteroides_ovatus ='#4363d8', 
                 Bacteroides_xylanisolvens='#f58231', Agathobacter_rectalis ='#911eb4', 
                 Anaerobutyricum_soehngenii ='#46f0f0', Eubacterium_siraeum ='#f032e6', 
                 Blautia_hydrogenotrophica='#bcf60c', Coprococcus_catus='#fabebe', 
                 Flavonifractor_plautiia ='#008080', Roseburia_intestinalis ='#e6beff', 
                 Faecalibacterium_prausnitzii ='#9a6324', Blautia_obeum= '#fffac8', 
                 Ruminococcus_bromii='#800000', Subdoligranulum_variabile='#aaffc3', 
                 Acetate = '#808000', Butyrate = '#ffd8b1', 
                 Formate = '#000075', Propionate = '#808080', 
                 Lactate = '#ffffff', Succinate = '#000000')

fasting_cols <- c("#C71585", "#008080")

fer_cols <- c(Bioreactor_5= "#b2182b", Bioreactor_6="#2166ac", Bioreactor_8 = "#35978f")
```



# Load data  
```{r eval=FALSE}
library(syncomR)
```


```{r eval=FALSE}
library(syncomR)
```


# utility  

```{r}
data(SyncomFiltData)
ps1.b5 <- subset_samples(SyncomFiltData, StudyIdentifier== "Bioreactor A")
remove_T80 <- c("Ferm_1_5_80", "Ferm_1_6_80", "Ferm_1_8_80")
ps1.sub <- prune_samples( !(sample_names(ps1.b5) %in% remove_T80), ps1.b5)
otu.tb <- taxa_time_table(ps1.sub, normalize = TRUE, time.col= 'Time_hr', remove.zero = TRUE)
head(otu.tb)
```

##

```{r}
data(SyncomFiltData)
fasting_cols <- c("#b3de69", "#fb8072", "#80b1d3")

pl <- taxa_coverage(SyncomFiltData, coverage = 0.9999,
                    time.column = "Time_hr_num",
                    shape.variable = "Acetate_Feed",
                    color.variable = "Fasting",
                    #facet.var = "StudyIdentifier",
                    color.pal = fasting_cols,
                    y.breaks = seq(0, 16, 1),
                    y.limits = c(9, 16))
pl + facet_wrap(~ StudyIdentifier)

```


### Generate time-taxa table  
```{r}
data(SyncomFiltData)
ps1.b5 <- subset_samples(SyncomFiltData, StudyIdentifier== "Bioreactor A")
remove_T80 <- c("Ferm_1_5_80", "Ferm_1_6_80", "Ferm_1_8_80")
ps1.sub <- prune_samples( !(sample_names(ps1.b5) %in% remove_T80), ps1.b5)
otu.tb <- taxa_time_table(ps1.sub, normalize = TRUE, time.col= 'Time_hr', remove.zero = TRUE)
head(otu.tb)
```



## Community composition  
```{r}
data(SyncomFiltData)
SyncomFiltData.rel <- microbiome::transform(SyncomFiltData, "compositional")
p <- plot_syncom_composition(SyncomFiltData.rel,
                         type = "bar",
                         time.col = "Time_hr_num",
                         taxa.level = "OTU",
                         sp.fill.pal = strain.colors, facet.var = "StudyIdentifier")
print(p)   
```

### Temporal turnover of communities    
```{r}
# Succession
p <- temporal_turnover(ps1.sub, tree =NULL,time.col = 'Time_hr_num', method = "canberra", compositional = TRUE)
#p + geom_label_repel() + theme_classic(base_size = 14)
dat <- p
```


# Succession  
```{r eval=FALSE}
library(syncomR)
```
